name: shuaishuaimovie
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  connectivity: ^0.4.9
  dio: ^3.0.9
  provider: ^4.1.3
  fluro: ^1.6.3
  sqflite: ^1.3.1
  cached_network_image: ^2.2.0+1
  fluttertoast: ^4.0.0
  flutter_easyrefresh: ^2.1.1
  flutter_sticky_header: ^0.4.5
  date_format: ^1.0.8
  animated_text_kit: ^2.2.0
  chewie: ^0.9.10
  video_player: ^0.10.11+2

  r_dart_library:
    git:
      url: https://github.com/YK-Unit/r_dart_library.git
      ref: 0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: appIconFonts
      fonts:
        - asset: assets/fonts/iconfont.ttf
flr:
  core_version: 3.1.0
  dartfmt_line_length: 80
  assets:

